Repository openshift/lightspeed-rag-content, pull requests merged in 2025-05, with the labels that each got.

#237 OLS-1499 Add script for removing ballast content from OpenShift documentation
  scripts/html_chunking/html-stripper.py
Labels: lgtm, approved, ok-to-test

#289 OLS-1651 Add script for fetching OpenShift documentation in the HTML format
  pdm.lock.cpu
  pdm.lock.gpu
  pyproject.toml
  scripts/asciidoctor-text/convert-it-all.py
  scripts/generate_packages_to_prefetch.py
  scripts/portal-fetcher/openshift-docs-downloader.py
  scripts/verify_rag_image_test.py
Labels: lgtm, approved, ok-to-test

#329 Update Konflux task references except for prefetch
  .tekton/lightspeed-rag-tool-pull-request.yaml
  .tekton/lightspeed-rag-tool-push.yaml
  .tekton/own-app-lightspeed-rag-content-pull-request.yaml
  .tekton/own-app-lightspeed-rag-content-push.yaml
Labels: lgtm, approved

#346 OLS-1340: add default symlink to the latest version of OCP docs
  Containerfile
Labels: jira/valid-reference, lgtm, approved

#334 Fix for the "--require-hashes mode" pip issue during BYOK tool build
  byok/Containerfile.output
  byok/Containerfile.tool
  byok/README.md
  byok/generate_embeddings_tool.py
  pdm.lock.cpu
  pdm.lock.gpu
  pyproject.toml
  requirements.cpu.txt
  requirements.gpu.txt
Labels: lgtm, approved

#362 OLS-1676: Create RAG BYOK tool image through Konflux
  .tekton/lightspeed-rag-tool-pull-request.yaml
  .tekton/lightspeed-rag-tool-push.yaml
  Makefile
  byok/Containerfile.output
  byok/Containerfile.tool
  rpms.in.yaml
  rpms.lock.yaml
  ubi.repo
Labels: jira/valid-reference, lgtm, approved
